version = 0.1

[default.deploy.parameters]
stack_name = "ttok-sun-i"
resolve_s3 = true
s3_prefix = "ttok-sun-i"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "SupabaseUrl=\"https://ladqubaousblucmrqcrr.supabase.co\" SupabaseServiceKey=\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZHF1YmFvdXNibHVjbXJxY3JyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODgyNDI1MiwiZXhwIjoyMDg0NDAwMjUyfQ.YZfsje16TIRzEKI9N6WgH-49XH-VPqLJwqwp4LlwhxY\" BedrockModelId=\"apac.amazon.nova-lite-v1:0\" TitanEmbeddingModelId=\"amazon.titan-embed-text-v2:0\""

[default.global.parameters]
region = "ap-northeast-2"
